function inv_G = ig_func(psi,theta,uv)
%IG_FUNC
%    inv_G = IG_FUNC(PSI,THETA,UV)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    01-May-2022 20:54:52

t2 = cos(psi);
t3 = cos(theta);
t4 = sin(psi);
t5 = sin(theta);
t6 = uv.^3;
t7 = t2.^2;
t8 = t3.^2;
t9 = t4.^2;
t10 = t5.^2;
t11 = t3.*t6.*t7.*(9.3e+1./5.0e+2);
t12 = t3.*t6.*t9.*(9.3e+1./5.0e+2);
t13 = t7.*t8.*(6.11e+2./1.0e+3);
t14 = t7.*t10.*(6.11e+2./1.0e+3);
t15 = t8.*t9.*(6.11e+2./1.0e+3);
t16 = t9.*t10.*(6.11e+2./1.0e+3);
t17 = t6.*t7.*t8.*(5.59e+2./1.0e+3);
t18 = t6.*t7.*t10.*(5.59e+2./1.0e+3);
t19 = t6.*t8.*t9.*(5.59e+2./1.0e+3);
t20 = t6.*t9.*t10.*(5.59e+2./1.0e+3);
t21 = t11+t12;
t23 = t13+t14+t15+t16;
t25 = t17+t18+t19+t20;
t22 = 1.0./t21;
t24 = 1.0./t23;
t26 = 1.0./t25;
inv_G = reshape([-t2.*t5.*t26,-t4.*t22,t2.*t3.*t24,-t4.*t5.*t26,t2.*t22,t3.*t4.*t24,-t3./(t6.*t8.*(5.59e+2./1.0e+3)+t6.*t10.*(5.59e+2./1.0e+3)),0.0,-t5./(t8.*(6.11e+2./1.0e+3)+t10.*(6.11e+2./1.0e+3))],[3,3]);
