function out1 = poly3(t)
%POLY3
%    OUT1 = POLY3(T)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    01-May-2022 20:27:04

out1 = [t.^2.*6.0e+1;t.*2.4e+1;6.0;0.0;0.0;0.0];
