function out1 = poly1(t)
%POLY1
%    OUT1 = POLY1(T)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    08-May-2022 20:41:18

out1 = [t.^4.*5.0;t.^3.*4.0;t.^2.*3.0;t.*2.0;1.0;0.0];
