function out1 = poly2(t)
%POLY2
%    OUT1 = POLY2(T)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-May-2022 21:16:06

out1 = [t.^3.*2.0e+1;t.^2.*1.2e+1;t.*6.0;2.0;0.0;0.0];
